$code = [System.Collections.Generic.List[string]]::new()
$code.Add("(function() {")
$code.Add("    'use strict';")
$code.Add("")
$code.Add("    // Mux protocol constants")
$code.Add("    const MUX_HEADER_SIZE = 9;")
$code.Add("    const MUX_TYPE_OUTPUT = 0x01;")
$code.Add("    const MUX_TYPE_INPUT = 0x02;")
$code.Add("    const MUX_TYPE_RESIZE = 0x03;")
$code.Add("    const MUX_TYPE_INIT = 0xFF;")
$code.Add("")
$code.Add("    // State")
$code.Add("    let sessions = [];")
$code.Add("    let activeSessionId = null;")
$code.Add("    let stateWs = null;")
$code.Add("    let stateReconnectTimer = null;")
$code.Add("    let stateReconnectDelay = 1000;")
$code.Add("    let muxWs = null;")
$code.Add("    let muxReconnectTimer = null;")
$code.Add("    let muxReconnectDelay = 1000;")
$code.Add("    let clientId = null;")
$code.Add("    let settingsOpen = false;")
$code.Add("    let currentSettings = null;")
$code.Add("    let sidebarOpen = false;")
$code.Add("    let notificationPermission = Notification.permission;")
$code.Add("")
$code.Add("    // Per-session state: { terminal, fitAddon, container, serverCols, serverRows }")
$code.Add("    const sessionTerminals = new Map();")
$code.Add("")
$code.Add("    // Theme definitions")
$code.Add("    const themes = {")
$code.Add("        dark: { background: '#1e1e1e', foreground: '#d4d4d4', cursor: '#ffffff', cursorAccent: '#1e1e1e', selectionBackground: '#264f78' },")
$code.Add("        light: { background: '#ffffff', foreground: '#1e1e1e', cursor: '#1e1e1e', cursorAccent: '#ffffff', selectionBackground: '#add6ff' },")
$code.Add("        solarizedDark: { background: '#002b36', foreground: '#839496', cursor: '#93a1a1', cursorAccent: '#002b36', selectionBackground: '#073642' },")
$code.Add("        solarizedLight: { background: '#fdf6e3', foreground: '#657b83', cursor: '#586e75', cursorAccent: '#fdf6e3', selectionBackground: '#eee8d5' }")
$code.Add("    };")
$code.Add("")
$code.Add("    // Cookie helpers for immediate theme availability")
$code.Add("    function setCookie(name, value, days = 365) {")
$code.Add("        const expires = new Date(Date.now() + days * 864e5).toUTCString();")
$code.Add("        document.cookie = name + '=' + encodeURIComponent(value) + '; expires=' + expires + '; path=/; SameSite=Lax';")
$code.Add("    }")
$code.Add("")
$code.Add("    function getCookie(name) {")
$code.Add("        const value = document.cookie.split('; ').find(row => row.startsWith(name + '='));")
$code.Add("        return value ? decodeURIComponent(value.split('=')[1]) : null;")
$code.Add("    }")
$code.Add("")
$code.Add("    // Apply theme from cookie immediately to prevent flash")
$code.Add("    const savedTheme = getCookie('mm-theme');")
$code.Add("    if (savedTheme && themes[savedTheme]) {")
$code.Add("        document.documentElement.style.setProperty('--terminal-bg', themes[savedTheme].background);")
$code.Add("    }")
[System.IO.File]::WriteAllLines("terminal_part1.txt", $code)
Write-Host "Part 1 written"
